### ISSUE TITLE
Add stricter CI linter for this repo

### ISSUE THREAD

**Issue by zzxwill** [crossplane/provider-alibaba#60]
### What problem are you facing?

Adding some stricter CI linters to help improve the quality of this code base.

**Comment by negz** [comment]
I'd love to aim to keep the linting standards _somewhat_ consistent across Crossplane projects. Providers can diverge if they think there's value in doing so, but it would be great to get feedback around what you think our linter is lacking at the moment and how it could be improved. This feedback could be useful to the broader Crossplane project.

https://github.com/crossplane/provider-alibaba/blob/master/.golangci.yml

**Comment by zzxwill** [comment]
Got it, thanks.
