### ISSUE TITLE
[featrue] supply alibaba cloud  database  for redis 

### ISSUE THREAD

**Issue by xiqiu618** [crossplane/provider-alibaba#69]
### What problem are you facing?

supply alibaba cloud  database  for redis

**Comment by zzxwill** [comment]
Refer to #67

**Comment by hzlml** [comment]
@xiqiu618 @zzxwill 
I see the task is pending for lacking of test cases, is this enhancement still in progress  ?

**Comment by zzxwill** [comment]
@hzlml The PR is merged.

Could anyone help close this issue? Thanks.

**Comment by wonderflow** [comment]
closing as it's supported now
