### ISSUE TITLE
Make helm chart

### ISSUE THREAD

**Issue by zzxwill** [crossplane/provider-alibaba#86]
Make a helm chart for this provider to enable the easy deployment of this controller.

**Comment by negz** [comment]
We do not typically support or recommend installing providers as Helm charts. The CI/CD for this repository already automatically creates a Crossplane provider package (i.e. a `Provider.pkg.crossplane.io`) to easily deploy this provider.

**Comment by zzxwill** [comment]
Got it. I will look into the development guide and support the installation by `kubectl crossplane install configuration xxx`.
